// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: places.proto

package api_grpc

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Place_PlaceType int32

const (
	Place_BAR        Place_PlaceType = 0
	Place_CAFE       Place_PlaceType = 1
	Place_RESTAURANT Place_PlaceType = 2
	Place_SHOP       Place_PlaceType = 3
	Place_STREET     Place_PlaceType = 4
	Place_SQUARE     Place_PlaceType = 5
	Place_BUILDING   Place_PlaceType = 6
	Place_LAKE       Place_PlaceType = 7
	Place_RIVER      Place_PlaceType = 8
	Place_MOUNTAIN   Place_PlaceType = 9
	Place_STATION    Place_PlaceType = 10
	Place_OUTDOOR    Place_PlaceType = 11
)

// Enum value maps for Place_PlaceType.
var (
	Place_PlaceType_name = map[int32]string{
		0:  "BAR",
		1:  "CAFE",
		2:  "RESTAURANT",
		3:  "SHOP",
		4:  "STREET",
		5:  "SQUARE",
		6:  "BUILDING",
		7:  "LAKE",
		8:  "RIVER",
		9:  "MOUNTAIN",
		10: "STATION",
		11: "OUTDOOR",
	}
	Place_PlaceType_value = map[string]int32{
		"BAR":        0,
		"CAFE":       1,
		"RESTAURANT": 2,
		"SHOP":       3,
		"STREET":     4,
		"SQUARE":     5,
		"BUILDING":   6,
		"LAKE":       7,
		"RIVER":      8,
		"MOUNTAIN":   9,
		"STATION":    10,
		"OUTDOOR":    11,
	}
)

func (x Place_PlaceType) Enum() *Place_PlaceType {
	p := new(Place_PlaceType)
	*p = x
	return p
}

func (x Place_PlaceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Place_PlaceType) Descriptor() protoreflect.EnumDescriptor {
	return file_places_proto_enumTypes[0].Descriptor()
}

func (Place_PlaceType) Type() protoreflect.EnumType {
	return &file_places_proto_enumTypes[0]
}

func (x Place_PlaceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Place_PlaceType.Descriptor instead.
func (Place_PlaceType) EnumDescriptor() ([]byte, []int) {
	return file_places_proto_rawDescGZIP(), []int{0, 0}
}

type Place struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location    string               `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Type        Place_PlaceType      `protobuf:"varint,4,opt,name=type,proto3,enum=places.Place_PlaceType" json:"type,omitempty"`
	Comment     string               `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	LastUpdated *timestamp.Timestamp `protobuf:"bytes,6,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
}

func (x *Place) Reset() {
	*x = Place{}
	if protoimpl.UnsafeEnabled {
		mi := &file_places_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_places_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_places_proto_rawDescGZIP(), []int{0}
}

func (x *Place) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Place) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Place) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Place) GetType() Place_PlaceType {
	if x != nil {
		return x.Type
	}
	return Place_BAR
}

func (x *Place) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Place) GetLastUpdated() *timestamp.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// The request message
type PlaceIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PlaceIdRequest) Reset() {
	*x = PlaceIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_places_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceIdRequest) ProtoMessage() {}

func (x *PlaceIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_places_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceIdRequest.ProtoReflect.Descriptor instead.
func (*PlaceIdRequest) Descriptor() ([]byte, []int) {
	return file_places_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// The response message
type PlaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PlaceResponse) Reset() {
	*x = PlaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_places_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceResponse) ProtoMessage() {}

func (x *PlaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_places_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceResponse.ProtoReflect.Descriptor instead.
func (*PlaceResponse) Descriptor() ([]byte, []int) {
	return file_places_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PlacesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*Place `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *PlacesResponse) Reset() {
	*x = PlacesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_places_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacesResponse) ProtoMessage() {}

func (x *PlacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_places_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacesResponse.ProtoReflect.Descriptor instead.
func (*PlacesResponse) Descriptor() ([]byte, []int) {
	return file_places_proto_rawDescGZIP(), []int{3}
}

func (x *PlacesResponse) GetPlaces() []*Place {
	if x != nil {
		return x.Places
	}
	return nil
}

var File_places_proto protoreflect.FileDescriptor

var file_places_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x02, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x9b, 0x01, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x41, 0x52, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x43, 0x41, 0x46, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x45, 0x53, 0x54, 0x41,
	0x55, 0x52, 0x41, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x48, 0x4f, 0x50, 0x10,
	0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x45, 0x45, 0x54, 0x10, 0x04, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x51, 0x55, 0x41, 0x52, 0x45, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x55, 0x49,
	0x4c, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x41, 0x4b, 0x45, 0x10,
	0x07, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x49, 0x56, 0x45, 0x52, 0x10, 0x08, 0x12, 0x0c, 0x0a, 0x08,
	0x4d, 0x4f, 0x55, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x0a, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x55, 0x54, 0x44, 0x4f,
	0x4f, 0x52, 0x10, 0x0b, 0x22, 0x20, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x37, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x32, 0x44, 0x0a, 0x06, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12,
	0x16, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73,
	0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e,
	0x69, 0x6b, 0x6c, 0x65, 0x6b, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x61,
	0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_places_proto_rawDescOnce sync.Once
	file_places_proto_rawDescData = file_places_proto_rawDesc
)

func file_places_proto_rawDescGZIP() []byte {
	file_places_proto_rawDescOnce.Do(func() {
		file_places_proto_rawDescData = protoimpl.X.CompressGZIP(file_places_proto_rawDescData)
	})
	return file_places_proto_rawDescData
}

var file_places_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_places_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_places_proto_goTypes = []interface{}{
	(Place_PlaceType)(0),        // 0: places.Place.PlaceType
	(*Place)(nil),               // 1: places.Place
	(*PlaceIdRequest)(nil),      // 2: places.PlaceIdRequest
	(*PlaceResponse)(nil),       // 3: places.PlaceResponse
	(*PlacesResponse)(nil),      // 4: places.PlacesResponse
	(*timestamp.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_places_proto_depIdxs = []int32{
	0, // 0: places.Place.type:type_name -> places.Place.PlaceType
	5, // 1: places.Place.lastUpdated:type_name -> google.protobuf.Timestamp
	1, // 2: places.PlacesResponse.places:type_name -> places.Place
	2, // 3: places.Places.GetById:input_type -> places.PlaceIdRequest
	3, // 4: places.Places.GetById:output_type -> places.PlaceResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_places_proto_init() }
func file_places_proto_init() {
	if File_places_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_places_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Place); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_places_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_places_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_places_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlacesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_places_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_places_proto_goTypes,
		DependencyIndexes: file_places_proto_depIdxs,
		EnumInfos:         file_places_proto_enumTypes,
		MessageInfos:      file_places_proto_msgTypes,
	}.Build()
	File_places_proto = out.File
	file_places_proto_rawDesc = nil
	file_places_proto_goTypes = nil
	file_places_proto_depIdxs = nil
}
